#!/bin/bash
pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
mkdir -p pokemon_data
max_retries=3
pids=()

for pokemon in "${pokemons[@]}"; do
	(
		echo "Fetching data for $pokemon..."

		filepath="pokemon_data/$pokemon.json"
		attempts=1
		success=false

		while [ "$attempts" -le "$max_retries" ]; do
			curl -s --fail https://pokeapi.co/api/v2/pokemon/"$pokemon"/ >"$filepath" 2>>errors.txt
			status=$?
			sleep 3
			if [ "$status" -eq 0 ]; then
				success=true
				break
			else
				echo "Attempt $attempts failed for $pokemon"
				((attempts++))
				echo "retrying..."
			fi
		done
		if [ "$success" = false ]; then
			echo "Failed to retrieve $pokemon. exit_code: $status" >>fetching_errors.txt
			rm -f "$filepath"
		else
			echo "Saved data to $filepath"
		fi
	) &

	pid=$!
	pids+=("$pid")
	echo "Started fetchin $pokemon on PID $pid"
done

while [ ${#pids[@]} -gt 0 ]; do
	# jobs

	running_pids=()

	for pid in "${pids[@]}"; do
		if kill -0 "$pid" 2>/dev/null; then
			running_pids+=("$pid")
		else
			echo "Process $pid has completed."
		fi
	done

	pids=("${running_pids[@]}")

	if [ ${#pids[@]} -gt 0 ]; then
		sleep 1
	fi
done

echo "All processes finished."
