#!/bin/bash
pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
mkdir -p pokemon_data

for pokemon in "${pokemons[@]}"; do
	echo "Fetching data for $pokemon..."

	filepath="pokemon_data/$pokemon.json"
	curl -s --fail https://pokeapi.co/api/v2/pokemon/"$pokemon"/ >"$filepath" 2>>errors.txt
	status=$?

	if [ "$status" -eq 0 ]; then
		echo "Saved data to $filepath"
	else
		echo "Failed to retrieve $pokemon. exit_code: $status"
		rm -f "$filepath"
	fi

	sleep 5
done
