#!/bin/bash
pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
mkdir -p pokemon_data
max_retries=3

for pokemon in "${pokemons[@]}"; do
	echo "Fetching data for $pokemon..."

	filepath="pokemon_data/$pokemon.json"
	attempts=1
	success=false

	while [ "$attempts" -le "$max_retries" ]; do
		curl -s --fail https://pokeapi.co/api/v2/pokemon/"$pokemon"/ >"$filepath" 2>>errors.txt
		status=$?
		if [ "$status" -eq 0 ]; then
			success=true
			break
		else
			echo "Attempt $attempts failed for $pokemon"
			((attempts++))
			echo "retrying..."
			sleep 2
		fi
	done
	if [ "$success" = false ]; then
		echo "Failed to retrieve $pokemon. exit_code: $status" >>fetching_errors.txt
		rm -f "$filepath"
	else
		echo "Saved data to $filepath"
	fi

	sleep 5
done
